# Model Comparison Lab

In this lab we will compare the performance of all the models we have learned about so far, using the car evaluation dataset.

## 1. Prepare the data

The [car evaluation dataset](https://archive.ics.uci.edu/ml/machine-learning-databases/car/) is in the assets/datasets folder. By now you should be very familiar with this dataset.

1. Load the data into a pandas dataframe
- Encode the categorical features properly: define a map that preserves the scale (assigning smaller numbers to words indicating smaller quantities)
- Separate features from target into X and y

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
df = pd.read_csv('../../assets/datasets/car.csv')
df.sample(10)

buying  maint  doors persons lug_boot safety acceptability
1373    low  vhigh      4    more      med   high           acc
270   vhigh    med      4       2    small    low         unacc
938     med  vhigh      4    more    small   high           acc
630    high   high  5more       4    small    low         unacc
1726    low    low  5more    more      big    med          good
224   vhigh    med      2       2      big   high         unacc
441    high  vhigh      2       4    small    low         unacc
70    vhigh  vhigh      4       4      big    med         unacc
992     med   high      2    more    small   high         unacc
205   vhigh   high  5more       4      big    med         unacc

In [6]:
map1 = {'low':1, 
       'med':2,
       'high':3,
       'vhigh':4}
map2 = {'small':1,
       'med':2,
       'big':3}
map3 = {'unacc':1,
       'acc':2,
       'good':3,
       'vgood':4}
map4 = {'2':2,
       '4':4,
       'more':5}
map5 = {'2':2,
       '3':3,
       '4':4,
       '5more':5}


In [8]:
features = [c for c in df.columns if c!= 'acceptability']
dfn = df.copy()

dfn.buying = df.buying.map(map1)
dfn.maint = df.maint.map(map1)
dfn.lug_boot = df.lug_boot.map(map2)
dfn.persons = df.persons.map(map4)
dfn.doors = df.doors.map(map5)
dfn.safety = df.safety.map(map1)
dfn.acceptability = df.acceptability.map(map3)

X = dfn[features]
y = dfn['acceptability']
X.head()

buying  maint  doors  persons  lug_boot  safety
0       4      4      2        2         1       1
1       4      4      2        2         1       2
2       4      4      2        2         1       3
3       4      4      2        2         2       1
4       4      4      2        2         2       2

In [9]:
dfn.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
buying           1728 non-null int64
maint            1728 non-null int64
doors            1728 non-null int64
persons          1728 non-null int64
lug_boot         1728 non-null int64
safety           1728 non-null int64
acceptability    1728 non-null int64
dtypes: int64(7)
memory usage: 94.6 KB


## 2. Useful preparation

Since we will compare several models, let's write a couple of helper functions.

1. Separate X and y between a train and test set, using 30% test set, random state = 42
    - make sure that the data is shuffled and stratified
2. Define a function called `evaluate_model`, that trains the model on the train set, tests it on the test, calculates:
    - accuracy score
    - confusion matrix
    - classification report
3. Initialize a global dictionary to store the various models for later retrieval


In [10]:
from sklearn.cross_validation import train_test_split, KFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report 

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 42, stratify = y)

def evaluate_model(model):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    
    a = accuracy_score(y_test, y_pred)
    
    cm = confusion_matrix(y_test, y_pred)
    cr = classification_report(y_test, y_pred)
    
    print cm
    print cr
    
    return a
all_models = {}


## 3.a KNN

Let's start with `KNeighborsClassifier`.

1. Initialize a KNN model
- Evaluate it's performance with the function you previously defined
- Find the optimal value of K using grid search
    - Be careful on how you perform the cross validation in the grid search

In [12]:
from sklearn.neighbors import KNeighborsClassifier
 
a = evaluate_model(KNeighborsClassifier())

[[354   9   0   0]
 [  8 107   0   0]
 [  0   9  11   1]
 [  0   2   0  18]]
             precision    recall  f1-score   support

          1       0.98      0.98      0.98       363
          2       0.84      0.93      0.88       115
          3       1.00      0.52      0.69        21
          4       0.95      0.90      0.92        20

avg / total       0.95      0.94      0.94       519



In [13]:
from sklearn.grid_search import GridSearchCV

params = {'n_neighbors': range(2,60)}

gsknn = GridSearchCV(KNeighborsClassifier(), 
                    params, n_jobs = -1, 
                     cv=KFold(len(y),n_folds=3,shuffle=True))

In [14]:
gsknn.fit(X, y)

GridSearchCV(cv=sklearn.cross_validation.KFold(n=1728, n_folds=3, shuffle=True, random_state=None),
       error_score='raise',
       estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform'),
       fit_params={}, iid=True, n_jobs=-1,
       param_grid={'n_neighbors': [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]},
       pre_dispatch='2*n_jobs', refit=True, scoring=None, verbose=0)

In [15]:
gsknn.best_params_

{'n_neighbors': 5}

In [17]:
gsknn.best_score_

0.95486111111111116

In [18]:
evaluate_model(gsknn.best_estimator_)

[[354   9   0   0]
 [  8 107   0   0]
 [  0   9  11   1]
 [  0   2   0  18]]
             precision    recall  f1-score   support

          1       0.98      0.98      0.98       363
          2       0.84      0.93      0.88       115
          3       1.00      0.52      0.69        21
          4       0.95      0.90      0.92        20

avg / total       0.95      0.94      0.94       519



0.94412331406551064

In [19]:
all_models['knn'] = {'model': gsknn.best_estimator_, 
                    'score':a}

## 3.b Bagging + KNN

Now that we have found the optimal K, let's wrap `KNeighborsClassifier` in a BaggingClassifier and see if the score improves.

1. Wrap the KNN model in a Bagging Classifier
- Evaluate performance
- Do a grid search only on the bagging classifier params

In [21]:
from sklearn.ensemble import BaggingClassifier

baggingknn = BaggingClassifier(KNeighborsClassifier())

evaluate_model(baggingknn)

[[354   9   0   0]
 [  8 107   0   0]
 [  0   8  12   1]
 [  0   2   0  18]]
             precision    recall  f1-score   support

          1       0.98      0.98      0.98       363
          2       0.85      0.93      0.89       115
          3       1.00      0.57      0.73        21
          4       0.95      0.90      0.92        20

avg / total       0.95      0.95      0.94       519



0.94605009633911363

In [23]:
bagging_params = {'n_estimators': [10,20],
                 'max_samples': [0.7, 1.0],
                 'max_features': [0.7, 1.0],
                 'boot_strap_features': [True, False]}

gsbaggingknn = GridSearchCV(baggingknn, bagging_params)

evaluate_model(gsbaggingknn)

ValueError: Invalid parameter boot_strap_features for estimator BaggingClassifier. Check the list of available parameters with `estimator.get_params().keys()`.

## 4. Logistic Regression

Let's see if logistic regression performs better

1. Initialize LR and test on Train/Test set
- Find optimal params with Grid Search
- See if Bagging improves the score

In [ ]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()

GridSearchCV(logreg, )

## 5. Decision Trees

Let's see if Decision Trees perform better

1. Initialize DT and test on Train/Test set
- Find optimal params with Grid Search
- See if Bagging improves the score

## 6. Support Vector Machines

Let's see if SVM perform better

1. Initialize SVM and test on Train/Test set
- Find optimal params with Grid Search
- See if Bagging improves the score

## 7. Random Forest & Extra Trees

Let's see if Random Forest and Extra Trees perform better

1. Initialize RF and ET and test on Train/Test set
- Find optimal params with Grid Search

## 8. Model comparison

Let's compare the scores of the various models.

1. Do a bar chart of the scores of the best models. Who's the winner on the train/test split?
- Re-test all the models using a 3 fold stratified shuffled cross validation
- Do a bar chart with errorbars of the cross validation average scores. is the winner the same?


## Bonus

We have encoded the data using a map that preserves the scale.
Would our results have changed if we had encoded the categorical data using `pd.get_dummies` or `OneHotEncoder`  to encode them as binary variables instead?

1. Repeat the analysis for this scenario. Is it better?
- Experiment with other models or other parameters, can you beat your classmates best score?