In [2]:
from sklearn.linear_model import LogisticRegression
import numpy as np

In [3]:
X = np.random.randn(100,3)
Y = np.random.binomial(1, 0.5, 100)

In [4]:
logreg = LogisticRegression()
logreg.fit(X,Y)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [5]:
logreg.coef_

array([[ 0.47854605,  0.17808018,  0.27841558]])

In [15]:
X_new = np.random.randn(100, 3)


In [16]:
# predict class:
y_pred = logreg.predict(X_new)
y_pred

array([0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1])

In [17]:
# predicted probability:
y_pp = logreg.predict_proba(X_new)
y_pp

array([[ 0.71925404,  0.28074596],
       [ 0.81249848,  0.18750152],
       [ 0.45359297,  0.54640703],
       [ 0.10529859,  0.89470141],
       [ 0.61172086,  0.38827914],
       [ 0.33123926,  0.66876074],
       [ 0.62391934,  0.37608066],
       [ 0.91752317,  0.08247683],
       [ 0.40460101,  0.59539899],
       [ 0.48976691,  0.51023309],
       [ 0.6297273 ,  0.3702727 ],
       [ 0.70606095,  0.29393905],
       [ 0.11576002,  0.88423998],
       [ 0.28655314,  0.71344686],
       [ 0.40945782,  0.59054218],
       [ 0.50020657,  0.49979343],
       [ 0.31163057,  0.68836943],
       [ 0.42320657,  0.57679343],
       [ 0.47674432,  0.52325568],
       [ 0.16289149,  0.83710851],
       [ 0.73920596,  0.26079404],
       [ 0.54471371,  0.45528629],
       [ 0.51133158,  0.48866842],
       [ 0.36715623,  0.63284377],
       [ 0.38059729,  0.61940271],
       [ 0.4418763 ,  0.5581237 ],
       [ 0.4550888 ,  0.5449112 ],
       [ 0.84600272,  0.15399728],
       [ 0.51197308,

In [18]:
import numpy as np
import pandas as pd
from sklearn.cross_validation import train_test_split
from sklearn.linear_model import LogisticRegression

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.33)

logreg = LogisticRegression()

logreg.fit(X_train, Y_train)
Y_pred = logreg.predict(X_test)

In [19]:
from sklearn.metrics import confusion_matrix

confusion = np.array(confusion_matrix(Y_test, Y_pred))
print confusion

[[ 9 10]
 [ 4 10]]


In [20]:
# calculate true positives, the number of 1s correctly predicted to be 1
TP = confusion[0,0]

# calculate false positives, the number of 0s incorrectly predicted to be 1
FP  = confusion[1,0]

# calculate true negatives, the number of 0s correctly predicted to be 0
TN = confusion[1,1]

# calculate false negatives, the number of 1s incorrectly predicted to be 0
FN = confusion[0,1]

In [21]:
from sklearn.metrics import accuracy_score
acs = accuracy_score(Y_test , Y_pred)
# This is equivalent to:
acc = np.sum(Y_test == Y_pred)/len(Y_test)

In [23]:
acc

0

In [26]:
from sklearn.metrics import classification_report

# Example printout:
print(classification_report(Y_test, Y_pred))

             precision    recall  f1-score   support

          0       0.69      0.47      0.56        19
          1       0.50      0.71      0.59        14

avg / total       0.61      0.58      0.57        33

