In [34]:
from sklearn.linear_model import LogisticRegression
import numpy as np

In [2]:
import numpy as np

In [35]:
X = np.random.randn(100, 3)

In [36]:
X

array([[  1.08482972e+00,   2.87769602e-02,  -1.09812106e+00],
       [ -7.91828747e-02,   7.87228618e-01,   4.35659496e-01],
       [ -7.46022361e-01,  -1.23455680e+00,   1.21267589e+00],
       [  2.02535469e-01,  -5.58896379e-01,  -6.62590045e-01],
       [ -3.08435609e-01,   4.01339295e-01,   1.76554635e+00],
       [ -3.74113550e-01,  -2.55573043e-01,   7.18118319e-01],
       [  1.10839696e-02,   9.87262459e-01,  -1.27634348e+00],
       [  1.05575091e+00,  -5.58397948e-01,   8.04144779e-01],
       [  5.24895561e-01,   1.37972915e+00,  -5.02309653e-01],
       [  1.96702689e+00,   3.45514575e-02,  -6.25251801e-01],
       [  7.95020959e-01,  -3.59268000e-01,  -8.10579444e-01],
       [  1.65480491e+00,  -8.18176822e-01,   1.88893084e+00],
       [  7.38116913e-01,  -4.10191175e-01,  -7.68275224e-04],
       [ -7.74810710e-01,  -9.02454484e-01,  -5.59165073e-01],
       [ -4.72369088e-01,   1.44974338e-01,   5.66507991e-01],
       [ -1.95434251e+00,   4.17130008e-01,   3.8862822

In [31]:
y = np.random.binomial(100, 0.05, 100)

In [32]:
y

array([ 7,  5,  9,  3,  6,  5,  4, 11, 10, 10,  5,  7,  6,  6,  4,  5,  2,
        6,  4,  5,  3,  1,  9,  5,  0,  8,  3,  4,  6,  7,  5,  4,  6,  6,
        4,  4,  5,  1,  5,  6,  2, 11,  6,  3, 10,  6,  6,  6,  4,  9,  3,
       10,  7,  5,  4,  7,  7,  5,  3,  6,  6,  2,  7,  7,  3,  7,  1,  4,
        3,  5,  6,  5,  6,  6,  2,  4,  1,  6,  5,  3,  2,  3,  5,  5,  3,
        6,  6,  8,  5,  8,  4,  4,  6,  5,  9,  6,  3,  6,  4,  1])

In [37]:
logreg = LogisticRegression()
logreg.fit(X,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [38]:
logreg.coef_

array([[-0.30148394,  0.18050051,  0.01458626],
       [-0.26593367, -0.19630355,  0.11261146],
       [ 0.54715284, -0.16500428, -0.0931747 ],
       [-0.08614052,  0.46183383,  0.3028066 ],
       [-0.31643586,  0.21913015,  0.1432037 ],
       [ 0.22414267, -0.10989699,  0.16593597],
       [-0.31454643, -0.26712544, -0.41515574],
       [ 0.34063281,  0.12308362, -0.04738408],
       [-0.21469194, -0.12535563, -0.21052567],
       [-0.30977418, -0.14281859,  0.1557534 ],
       [ 0.27584753,  0.18256379, -0.13340863],
       [ 0.10450656,  0.25955739,  0.07407301]])

In [39]:
X_new = np.random.randn(100,3)

In [40]:
y_pred = logreg.predict(X_new)

In [41]:
y_pp = logreg.predict_proba(X_new)

In [42]:
y_pred

array([6, 6, 5, 6, 6, 4, 3, 6, 3, 6, 5, 6, 6, 6, 5, 6, 5, 6, 4, 4, 6, 6, 6,
       6, 6, 6, 3, 6, 6, 6, 6, 5, 6, 5, 6, 6, 5, 5, 6, 6, 6, 5, 6, 6, 5, 5,
       6, 5, 6, 6, 7, 3, 6, 4, 5, 5, 6, 3, 6, 3, 5, 3, 6, 6, 6, 3, 4, 6, 5,
       6, 6, 5, 6, 6, 6, 6, 6, 3, 5, 3, 6, 4, 6, 6, 4, 5, 6, 6, 6, 6, 3, 6,
       6, 6, 6, 6, 6, 6, 6, 6])

In [43]:
y_pp

array([[ 0.03630223,  0.07024645,  0.04006104, ...,  0.06191118,
         0.04177886,  0.03249609],
       [ 0.03086882,  0.06148016,  0.05996979, ...,  0.05319191,
         0.05228747,  0.03813119],
       [ 0.0352662 ,  0.05812825,  0.04732981, ...,  0.05347311,
         0.05163776,  0.04519528],
       ..., 
       [ 0.02860586,  0.06991703,  0.0624879 , ...,  0.05956507,
         0.04600062,  0.03369509],
       [ 0.04839793,  0.08166606,  0.01822384, ...,  0.07941563,
         0.0282551 ,  0.03176151],
       [ 0.03978168,  0.04156877,  0.044461  , ...,  0.03715463,
         0.06936718,  0.04659368]])

In [44]:
lists = ['apple', 'orange', 'banana']

In [45]:
lists.append('carrot')

In [46]:
lists


['apple', 'orange', 'banana', 'carrot']

In [47]:
lists.extend(['dog', 'cow'])

In [48]:
lists

['apple', 'orange', 'banana', 'carrot', 'dog', 'cow']

In [49]:
lists.insert(1, 'crocodile')

In [50]:
lists

['apple', 'crocodile', 'orange', 'banana', 'carrot', 'dog', 'cow']

In [51]:
lists.remove('carrot')

In [52]:
lists


['apple', 'crocodile', 'orange', 'banana', 'dog', 'cow']

In [53]:
lists.sort()

In [54]:
lists

['apple', 'banana', 'cow', 'crocodile', 'dog', 'orange']

In [55]:
lists.count('a')

0