In [9]:
from sklearn.datasets import load_iris

In [10]:
iris = load_iris()
print iris

{'target_names': array(['setosa', 'versicolor', 'virginica'], 
      dtype='|S10'), 'data': array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.

In [11]:
iris.target #ones and zeros categorical means a classification problem as opposed to regression

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
type(iris)

sklearn.datasets.base.Bunch

In [13]:
print iris.feature_names

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [14]:
print iris.data.shape

(150, 4)


In [6]:
print iris.target_names

['setosa' 'versicolor' 'virginica']


In [18]:
'''scikit learn expects 4 key responses or inputs when 1) expects features and response to be passed into 
the machine learning model as seperate objects
2) expects only numerical values hence the binary 1s and 0s for the target names
3) scikit expects the numbers to be numpy arrays
4) feature and response objects are expected to have a certain shape'''

X = iris.data
y = iris.target


In [19]:
print X.shape

(150, 4)


In [16]:
print y.shape

(150,)


 ## SCIKIT LEARN 4 STEP MODELING PATTERN

- # STEP 1 import the class you plan to use

In [17]:
from sklearn.neighbors import KNeighborsClassifier

# STEP 2 'INSTANTIATE' the 'ESTIMATOR'
 - ESTIMATOR is scikits term for model (estimate unknown quantities)
- "INSTANTIATE means make an instance of"

In [22]:
knn = KNeighborsClassifier(n_neighbors=1) # 1 = the number of neighbors to look for an estimate

# STEP 3 :FIT THE MODEL WITH DATA(AKA"Model Training")
    -  model is learning the relationship btwn X and Y 
      - occurs inplace ### means we do not neet to assign the results

In [23]:
knn.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [26]:
knn.predict([3,5,4,2])

//anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([2])

# STEP 4: PREDICT THE RESPONSE FOR A NEW OBSERVATION
 - New observation are called 'out of sample' data
    - Uses the information it learned during the model training process

In [24]:
X_new = [[3,5,4,2], [5,4,3,2]]
knn.predict(X_new)    # here were asking the model to make 2 predictions on 2 diff sets of data
                       # The [2,1] response means the first flower is a 'versicolor' and the 2nd is 'virginica'


array([2, 1])

# CHANGING THE K VALUE


In [29]:
knn = KNeighborsClassifier(n_neighbors = 5)

In [30]:
knn.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [31]:
knn.predict(X_new)  # when we change the number of k neighbots we get a diff prediction

array([1, 1])

 - # USING A DIFFERENT CLASSIFICATION METHOD

In [32]:
# importing the class from the the data base

from sklearn.linear_model import LogisticRegression

In [33]:
# instantiating the model using the default parameters
logreg = LogisticRegression()

In [34]:
# fitting our data to the model
logreg.fit(X,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [35]:
# predicting our response for the new dataset
logreg.predict(X_new)

array([2, 0])

MODEL EVALUATION PROCEDURES

- # EVALUATION PROCEDURE # 1
    - train and test on entire dataset
     - Test the data on the same dataset
    

In [37]:
# import the class
from sklearn.linear_model import LogisticRegression

#instantiate the model using the default parameters
logreg = LogisticRegression()

#fit the data to the model
logreg.fit(X,y)

#make a prediction 
logreg.predict(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1,
       1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [38]:
y_pred = logreg.predict(X)
len(y_pred)

150

# CLASSIFICATION ACCURACY 
 - PROPORTION OF OUR CORRECT PREDICTIONS
    - COMMON ELALUATION METRIC FOR CLASSIFICATION PROBLEMS