# Decision Trees 

- Can be applied to both classification and regression problems
- Upside down tree
- Root, Internal(branches), Terminal(leaves) nodes


# Regression
- Recursive binary splitting the split that minimizes the sum of the squared deviations(RSS) from the mean in the two separate partitions.
- A top down greedy approach(best at the time doesn't look ahead)
- can lead to overfitting pruning is needed via cross validation

![alt text](regressiontreeinr.png "Title")

# Classification Tree
- similar to regression but qualitative not quantitative.
- Instead of RSS it can use classification error rate, cross-entropy or, most favorable, the Gini index.
- Gini index scored on node purity. What proportion of the observations in the node from the same class. A score is taken at each split.

In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.cross_validation import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
 

//anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
iris = load_iris()
X= iris.data
y= iris.target

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3)


In [25]:
dtree = DecisionTreeClassifier()
f = dtree.fit(X_train,y_train)


In [5]:
y_pred = dtree.predict(X_test)

In [30]:
print confusion_matrix(y_test, y_pred)
print '\n'
print classification_report(y_test, y_pred)
print 

[[15  0  0]
 [ 0 11  0]
 [ 0  0 19]]


             precision    recall  f1-score   support

          0       1.00      1.00      1.00        15
          1       1.00      1.00      1.00        11
          2       1.00      1.00      1.00        19

avg / total       1.00      1.00      1.00        45

[ 0.01228434  0.03347909  0.00882965  0.94540692]


# A reason for decision trees

- non linear boundaries

![alt text](classdemo_03.png "Title")

# Advantages of DT
- Easy to explain and interpret. 
- Resembles yes/no, left/right familiar to human decision making 

# Disadvantages

- Lack prediction accuracy seen in other models
- suffer from high variance. If we split the training data into two parts at random, and fit a decision tree to both halves, the results that we get could be quite different. 

# How can decision trees be improved?
- Bootstrap aggregating(bagging), Boosting and Random Forests

# Bagging
- taking repeated samples from the (single) training data set to decrease variance. 
- Number of estimators should not matter as bagging is not known to overfit
- bagging improves prediction accuracy at the expense of interpretability. (no single tree)

In [7]:
from sklearn.ensemble import BaggingClassifier

In [8]:
bag = BaggingClassifier(DecisionTreeClassifier())
bag.fit(X,y)

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=1.0, n_estimators=10, n_jobs=1, oob_score=False,
         random_state=None, verbose=0, warm_start=False)

In [9]:
y_pred = bag.predict(X_test)

In [10]:
print confusion_matrix(y_test, y_pred)
print '\n'
print classification_report(y_test, y_pred)

[[15  0  0]
 [ 0 11  0]
 [ 0  0 19]]


             precision    recall  f1-score   support

          0       1.00      1.00      1.00        15
          1       1.00      1.00      1.00        11
          2       1.00      1.00      1.00        19

avg / total       1.00      1.00      1.00        45



# Boosting
- Instead of growing each tree individually and combining to make the best predictor like bagging. Boosting grows it's trees sequentially 
- each tree is grown using information from previously grown trees. Boosting does not involve bootstrap sampling; instead each tree is fit on a modified version of the original data set.
- fits new trees to areas where there is poor performance. Thus, it can lead to overfitting


In [11]:
from sklearn.ensemble import AdaBoostClassifier

In [12]:
ada = AdaBoostClassifier()
ada.fit(X,y)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [13]:
y_pred = ada.predict(X_test)


In [14]:
print confusion_matrix(y_test, y_pred)
print '\n'
print classification_report(y_test, y_pred)

[[15  0  0]
 [ 0 10  1]
 [ 0  3 16]]


             precision    recall  f1-score   support

          0       1.00      1.00      1.00        15
          1       0.77      0.91      0.83        11
          2       0.94      0.84      0.89        19

avg / total       0.92      0.91      0.91        45



# Random Forest(tm)
- Similar to bagging, we build a number of decision trees on bootstrapped training samples. 
- Different because we do not use all of the features unlike bagging. 
- This process aims to level the playing field by not continuously placing one very strong predictor in the data set at the root node, but rather, use the strong predictor along with a number of other moderately strong predictors.
- Random Forest is not susceptible to overfitting

In [15]:
from sklearn.ensemble import RandomForestClassifier

In [16]:
rfc = RandomForestClassifier()
rfc.fit(X,y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

In [17]:
y_pred = rfc.predict(X_test)

In [18]:
print confusion_matrix(y_test, y_pred)
print '\n'
print classification_report(y_test, y_pred)

[[15  0  0]
 [ 0 11  0]
 [ 0  0 19]]


             precision    recall  f1-score   support

          0       1.00      1.00      1.00        15
          1       1.00      1.00      1.00        11
          2       1.00      1.00      1.00        19

avg / total       1.00      1.00      1.00        45

