In [1]:
import numpy as np
x = np.array([1,3,5,7,9])

In [2]:
np.shape(x)

(5,)

In [3]:
x.shape

(5,)

In [14]:
y = np.array([[1,2,3,4,5,6],[4,5,6,7,8,9]])

In [15]:
y.shape

(2, 6)

In [16]:
y.reshape(2,6)

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8, 9]])

In [17]:
y.reshape(1,12)

array([[1, 2, 3, 4, 5, 6, 4, 5, 6, 7, 8, 9]])

In [62]:
y = y.T

In [78]:
y[:4]

array([[1, 4],
       [2, 5],
       [3, 6],
       [4, 7]])

In [27]:
y[:,-2]

array([5, 8])

In [40]:
y[1:,5:]

array([[9]])

In [79]:
y


array([[1, 4],
       [2, 5],
       [3, 6],
       [4, 7],
       [5, 8],
       [6, 9]])

In [83]:
greater_than_three =  y[1,y[0] > 3]

In [84]:
print(greater_than_three)

[[4]]


In [66]:
y[1:4]

array([[2, 5],
       [3, 6],
       [4, 7]])

In [67]:
y[y>3]

array([4, 5, 6, 4, 7, 5, 8, 6, 9])

In [89]:
function = np.array([3,34,56,6,78,8,39])
def get_var(array):
    x_var = array.var()
    print(x_var)
    x_sd = x_var ** .5
    print(x_sd)


get_var(function)

691.142857143
26.2895959867


In [90]:
a = ["h","f","d","j"]
b = ['z','x','l','f','m']


In [92]:
for ads, bs in zip(a,b):
    print(ads, "I Like the same index as my self:", bs)
    

h I Like the same index as my self: z
f I Like the same index as my self: x
d I Like the same index as my self: l
j I Like the same index as my self: f


In [93]:
Officers = {'Michael Mulligan': 'Red Army',
            'Steven Johnson': 'Blue Army',
            'Jessica Billars': 'Green Army',
            'Sodoni Dogla': 'Purple Army',
            'Chris Jefferson': 'Orange Army'}

In [95]:
Officers

{'Chris Jefferson': 'Orange Army',
 'Jessica Billars': 'Green Army',
 'Michael Mulligan': 'Red Army',
 'Sodoni Dogla': 'Purple Army',
 'Steven Johnson': 'Blue Army'}

In [97]:
{keys:Officers[keys] for keys in Officers if not keys.startswith("Chris")}

{'Jessica Billars': 'Green Army',
 'Michael Mulligan': 'Red Army',
 'Sodoni Dogla': 'Purple Army',
 'Steven Johnson': 'Blue Army'}

In [99]:
Officers['Jessica Billars']

'Green Army'